version: '3'
services:
  sandbox-postgres:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=POSTGRES_DB
